version: "3"

services:
    web-mydata:
        container_name: web-mydata
        image: kota105/docker-laravel:web-mydata-release
        build: .
        ports:
            - "80:80"
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - web-network

    db:
        container_name: db
        image: postgres:latest
        ports:
            - "5434:5434"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - web-volume:/var/lib/postgresql/data
        networks:
            - web-network

volumes:
    web-volume: {}

networks:
    web-network:
